# Generated by Django 3.0.5 on 2020-08-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='사용자명')),
                ('password', models.CharField(max_length=32, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Stretagy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stret_name', models.CharField(max_length=128, verbose_name='전략명')),
                ('stret_num', models.IntegerField(unique=True, verbose_name='전략고유번호')),
                ('stret_descript', models.TextField(verbose_name='전략설명')),
                ('investment', models.IntegerField(verbose_name='투자원금')),
                ('ivm_dttm_s', models.DateTimeField(verbose_name='투자 시작일')),
                ('ivm_dttm_e', models.DateTimeField(verbose_name='투자 마감일')),
                ('max_stock_num', models.IntegerField(verbose_name='최대 보유 종목수')),
                ('u_market_cap', models.IntegerField(verbose_name='대상기업 최소시가총액')),
                ('u_roe', models.IntegerField(blank=True, verbose_name='최저 ROE')),
                ('u_roa', models.IntegerField(blank=True, verbose_name='최저 ROA')),
                ('u_salesPerProfit', models.IntegerField(blank=True, verbose_name='매출액대비 순이익률')),
                ('u_salesPerMargin', models.IntegerField(blank=True, verbose_name='매출액 대비 영업이익률')),
                ('u_salesIncrease', models.IntegerField(blank=True, verbose_name='매출액 증가율')),
                ('u_marginIncrease', models.IntegerField(blank=True, verbose_name='영업이익 증가율')),
                ('u_profitIncrease', models.IntegerField(blank=True, verbose_name='순이익 증가율')),
                ('u_debtRatio', models.IntegerField(blank=True, verbose_name='부채비율')),
                ('u_currentRatio', models.IntegerField(blank=True, verbose_name='유동비율')),
                ('u_oaCashFlow', models.BooleanField(blank=True, verbose_name='영업활동현금흐름')),
                ('u_iaCashFlow', models.BooleanField(blank=True, verbose_name='투자활동현금흐름')),
                ('u_maCashFlow', models.BooleanField(blank=True, verbose_name='재무활동현금흐름')),
                ('u_eps_s', models.IntegerField(blank=True, verbose_name='주당순이익(min)')),
                ('u_eps_e', models.IntegerField(blank=True, verbose_name='주당순이익(max)')),
                ('u_bps_s', models.IntegerField(blank=True, verbose_name='주당순자산(min)')),
                ('u_bps_e', models.IntegerField(blank=True, verbose_name='주당순자산(max)')),
                ('u_cfps_s', models.IntegerField(blank=True, verbose_name='주당현금흐름(min)')),
                ('u_cfps_e', models.IntegerField(blank=True, verbose_name='주당현금흐름(max)')),
                ('u_sps_s', models.IntegerField(blank=True, verbose_name='주당매출액(min)')),
                ('u_sps_e', models.IntegerField(blank=True, verbose_name='주당매출액(max)')),
                ('u_dps_s', models.IntegerField(blank=True, verbose_name='주당배당금(min)')),
                ('u_dps_e', models.IntegerField(blank=True, verbose_name='주당배당금(max)')),
                ('u_per_s', models.IntegerField(blank=True, verbose_name='주가수익배수(min)')),
                ('u_pbr_s', models.IntegerField(blank=True, verbose_name='주가수익배수(min)')),
                ('u_pcr_s', models.IntegerField(blank=True, verbose_name='주가수익배수(min)')),
                ('u_psr_s', models.IntegerField(blank=True, verbose_name='주가수익배수(min)')),
                ('u_marketDiviend_s', models.IntegerField(blank=True, verbose_name='시가 배당률(min)')),
                ('u_marketDiviend_e', models.IntegerField(blank=True, verbose_name='시가 배당률(max)')),
                ('purc_cond', models.IntegerField(verbose_name='매수조건(%)')),
                ('targ_price', models.IntegerField(verbose_name='목표가격')),
                ('sell_price', models.IntegerField(verbose_name='손절가격')),
                ('reval_trm', models.IntegerField(verbose_name='리벨런싱 주기 ( 0:분기별 | 1:연간 | 2:선택안함 )')),
                ('writer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.User', verbose_name='전략작성자명')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Stretagy',
                'db_table': 'Stretagy',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_all', models.IntegerField(verbose_name='총 손익')),
                ('currentAsset', models.IntegerField(verbose_name='현재자산')),
                ('cagr', models.IntegerField(verbose_name='누적수익률')),
                ('m_cagr', models.IntegerField(verbose_name='월간수익률')),
                ('stretagy_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Stretagy', to_field='stret_num', verbose_name='전략 고유번호당 결과')),
                ('writer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.User', to_field='username', verbose_name='전략 작성자명')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'Results',
                'db_table': 'Results',
            },
        ),
    ]
