# Generated by Django 2.2.1 on 2020-07-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_validate',
        ),
    ]
