# Generated by Django 3.0.5 on 2020-08-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stra_name', models.CharField(max_length=128, verbose_name='전략명')),
                ('principal', models.IntegerField(verbose_name='투자 원금')),
                ('profit', models.IntegerField(verbose_name='손익')),
                ('curr_asset', models.IntegerField(verbose_name='현재 자산')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.Users', verbose_name='사용자명')),
            ],
            options={
                'verbose_name': '리턴값',
                'verbose_name_plural': '리턴값',
                'db_table': '유저,전략별 리턴 파라미터',
            },
        ),
    ]
